background_opacity 0.2

# BEGIN_KITTY_THEME
# 3024 Night
include current-theme.conf
# END_KITTY_THEME

font_family JetBrainsMono Nerd Font
bold_font JetBrainsMono Nerd Font Bold
italic_font JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic

symbol_map U+1F300-U+1F5FF Apple Color Emoji
symbol_map U+1F600-U+1F64F Apple Color Emoji
symbol_map U+1F680-U+1F6FF Apple Color Emoji
symbol_map U+1F1E6-U+1F1FF Apple Color Emoji

cursor_shape beam
cursor_beam_thickness 1.5
cursor_underline_thickness 2.0
cursor_blink_interval 0.6

enable_audio_bell yes

